### ISSUE TITLE
Versioning Interoperability?

### ISSUE THREAD

**Issue by j3ffgray** [CRASHSpace/COVID-19-3dprints#4]
To confirm, is care being taken to make sure masks made in one version still snap together with previous versions? I just finished printing a run of medium masks, but hadn't begun printing the cap and grid, and am hoping to prevent time and material wastage by printing items that won't couple up.

Are their "patch notes" someplace that describe the updates being made between versions?

**Comment by netkruzer** [comment]
Yes, the older versions of the face mask fit the new grid and new cap. They changed the number of slits on the cap.

**Comment by j3ffgray** [comment]
Great, thanks, just wanted to make sure!
