### ISSUE TITLE
Fiberglass in mask filters

### ISSUE THREAD

**Issue by sam598** [CRASHSpace/COVID-19-3dprints#5]
There are some air filters that contain fiberglass and should not be disassembled and used in masks. (https://www.reddit.com/r/3Dprinting/comments/ftmgtp/3d_printing_respirator_masks_be_aware_filters_can/)

Does anyone know if the filters linked in the readme (https://www.amazon.com/Flintar-Replacement-Compatible-Honeywell-HRF201B/dp/B07SQ5NHJ7/ref=sr_1_5?pldnSite=1) contain fiberglass? Should any special precautions be taken when cutting or using these masks? Should all "true-hepa" filters be okay to use?

**Comment by netkruzer** [comment]
I've bought a couple of these packs and taken them apart. They do not have the standard fiberglass in them that other wall type filters have. 

As for other HEPA filters, I can't say for sure. The ones you listed on Amazon only have some glue to deal with.

**Comment by netkruzer** [comment]
Also, these HEPA filters were recommended to us by USC Keck Medicine.

**Comment by sam598** [comment]
Thanks @netkruzer 

I will close this for now. I would be interested to hear if there are any updates or alternative filters.

**Comment by netkruzer** [comment]
It's a good question to ask. Don't want people endangering themselves with the wrong filters.
